#! /bin/bash

# Find all jupyter reports and
# convert them into html documents

find ./work \
    -maxdepth 1 \
    -type f \
    | xargs -d '\n' \
        jupyter nbconvert \
        --to html \
        --output-dir='./docs' \
