#! /bin/bash

# Find all jupyter reports and
# convert them into html documents

jupyter nbconvert \
        --to html \
        --output-dir='./docs' \
        --TemplateExporter.exclude_input=True \
        --TemplateExporter.exclude_input_prompt=True \
        ./work/*.ipynb
